Config:
  RobotName: gr2        # gr1 / gr2 / gr3 / fouriern1
  HardwareType: null    # null for gr2 and fouriern1; v211, v222 or v224 for gr3
  RunType: 1            # 0 run simulator / 1 control real robot
  UseJoyStick: true     # use as default
  DomainID: 123         # use as default

